@base_endpoint = http://localhost:8000/webhooks/payments
@provider_signature = LTExNDQxOTQwMzU=

### Receives a payment notification to update internal data.
### The intend of this endpoint is to act as a webhook to update internal data based
### on the payment gateway notification.
### For this endpoint to work, you must provide a valid signature, which needs to be hashed
### using a similar HMAC algorithm It is being used to check the signature. I suggest skipping this one ;)
### Returns a 204 NO_CONTENT in case of success.
POST {{base_endpoint}}
Content-Type: application/json
X-Provider-Signature: {{provider_signature}}

{
  "paymentId": "1",
  "paymentStatus": "Canceled"
}
