@base_endpoint = http://localhost:8000/auth

### Allows a new customer user to register for an account.
### Returns a 204 CREATED response in case of success.
POST {{base_endpoint}}/register/users/customers
Content-Type: application/json

{
	"name": "Victor Figueiredo Mendes",
	"email": "victor7@email.com",
	"password": "victor123!"
}

### Allows a user to log in using their email and password. Inactive users cannot log in.
### Returns a 200 OK response in case of success.
POST {{base_endpoint}}/login/users
Content-Type: application/json

{
	"email": "victor7@email.com",
	"password": "victor123!"
}

### Log in as an administrator.
### Returns a 200 OK response in case of success.
POST {{base_endpoint}}/login/users
Content-Type: application/json

{
  "email": "admin@email.com",
	"password": "admin123"
}

### Log in as the internal carrier
### Returns a 200 ok response in case of success.
POST {{base_endpoint}}/login/carriers
Content-Type: application/json

{
  "email": "carrier@email.com",
	"password": "carrier123"
}
