@base_endpoint = http://localhost:8000/auth

### Register a new user.
POST {{base_endpoint}}/register
Content-Type: application/json

{
	"name": "Victor Figueiredo Mendes",
	"email": "victor7@email.com",
	"password": "victor123!"
}

### Login as the new user. Inactive users can't login.
POST {{base_endpoint}}/login
Content-Type: application/json

{
	"email": "victor7@email.com",
	"password": "victor123!"
}

### Login as an administrator.
POST {{base_endpoint}}/login
Content-Type: application/json

{
  "email": "admin@email.com",
	"password": "admin123"
}
