@base_endpoint = http://localhost:8000/products
@token = insert-token-here
@id_product = 2

### Creates a new product. Admin authentication is required.
### Returns a 201 CREATED response in case of success.
POST {{base_endpoint}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Mens Cotton Jacket",
  "description": "Great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions.",
  "initialQuantity": 50,
  "basePrice": 200,
  "categoryIds": ["1"],
  "images": ["jacket.png"]
}

### Updates the details of an active product. Admin authentication is required.
### Returns a 204 NO_CONTENT response in case of success.
PUT {{base_endpoint}}/{{id_product}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Mens Cotton Jacket - Black",
  "description": "Great outerwear jackets for Spring/Autumn/Winter.",
  "basePrice": 250,
  "images": [
    "jacket.png",
    "jacket-behind.png"
  ],
  "categoryIds": ["1"]
}


### Increases the quantity available in inventory for an active product.
### Admin authentication is required.
### Returns a 204 NO_CONTENT response in case of success.
PUT {{base_endpoint}}/{{id_product}}/inventory
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantityToAdd": 25
}

### Deactivates a product and set the inventory to 0 items. Admin authentication is required.
### Returns a 204 NO_CONTENT response in case of success.
DELETE {{base_endpoint}}/{{id_product}}
Authorization: Bearer {{token}}

### Retrieves a paginated list of active products.
### Optional filters:
### - `category={id_category}`: Filters products by category.
### - `page={number}` (default: 1): Specifies the page number.
### - `pageSize={number}` (default: 20): Defines the number of products per page.
### No authentication required.
### Returns a 200 OK response in case of success.
GET {{base_endpoint}}?category=1&page=1&pageSize=20

### Retrieves an active product by its identifier. No authentication is required.
### Returns a OK response in case of success.
GET {{base_endpoint}}/{{id_product}}
