@host = http://localhost:8000

POST {{host}}/auth/register
Content-Type: application/json
{
	"name": "Victor Figueiredo Mendes",
	"email": "victor7@email.com",
	"password: "victor123!",
}

###
POST {{host}}/auth/login
Content-Type: application/json
{
  "email": "victor7@email.com",
	"password: "victor123!",
}
