@token_customer = insert-token-here
@token_admin = insert-token-here
@id_order = 1
@id_order_owner = 2
@base_orders_endpoint = http://localhost:8000/orders
@base_customer_orders_endpoint = http://localhost:8000/users/customers/{{id_order_owner}}/orders

### Places an order for a customer. Customer authentication is required.
### Returns a 201 CREATED response in case of success.
POST {{base_orders_endpoint}}
Content-Type: application/json
Authorization: Bearer {{token_customer}}
X-Idempotency-Key: dc6f84e4-0afb-42d4-b72a-261974c3d010

{
  "shippingMethodId": "1",
  "products": [
    {
      "productId": "1",
      "quantity": 2
    }
  ],
  "billingAddress": {
    "postalCode": "47305",
    "street": "2856 Overlook Drive",
    "state": "IN",
    "city": "Muncie",
    "neighborhood": "Grove Street, home"
  },
  "deliveryAddress": {
    "postalCode": "47305",
    "street": "2856 Overlook Drive",
    "state": "IN",
    "city": "Muncie",
    "neighborhood": "Grove Street, home"
  },
  "paymentMethod": {
    "$type": "CreditCard",
    "token": "tokenized-credit-card-data"
  },
  "couponAppliedIds": [],
  "installments": 1
}

### Retrieves all the orders. Administrator authentication is required.
### Returns an 200 OK response in case of success.
GET {{base_orders_endpoint}}
Authorization: Bearer {{token_admin}}

### Retrieves an order by its identifier. Admin authentication is required.
### Returns an 200 OK response in case of success.
GET {{base_orders_endpoint}}/{{id_order}}
Authorization: Bearer {{token_admin}}

### Retrieves all orders related to a customer. Self or admin authentication is required.
### Returns a 200 OK response in case of success.
GET {{base_customer_orders_endpoint}}
Authorization: Bearer {{token_admin}}

### Retrieves a customer's order by its identifier. Self or admin authentication is required.
### Returns a 200 OK response in case of success.
GET  {{base_customer_orders_endpoint}}/{{id_order}}
Authorization: Bearer {{token_admin}}
